### ISSUE TITLE
Reduce bundle size of @middy/validator

### ISSUE THREAD

**Issue by vekaev** [middyjs/middy#1004]
**Is your feature request related to a problem? Please describe.**
I analyzed bundle size of my lambda and I found that after adding `transpileSchema` function in middy v4 my bundle size increased from 30 kb to 132 kb
Yes, I know that it is kind of bundlephobia, but it's a huge difference
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/54939386/216765472-eacf5bcb-7db3-4112-96d4-e9d499d24450.png">

[Code](https://github.com/vekaev/educ_sls_auctions/blob/master/src/utils/middleware.helpers.ts)

What do u think about it?

**Comment by willfarrell** [comment]
Yeah, the code to compile json schema is a little on the chunky side. We added a lot more functionality in for v4 to make DX better and cover more use cases. It's a hard balance to find.

In the docs I mention that using `transpileSchema` inline will have a noticeable cold start hit to pre-compile a json schema. Because of this I recommend pre-transpiling (https://middy.js.org/docs/middlewares/validator#pre-transpiling-example-recommended). It's an extra build step, but will reduce your bundle size and make cold start faster.

I'm always thinking on how it could be better, but haven't had any good ideas yet (beside writing my own json schema package, but that a loooot of work). Open to ideas if you have any.
