### ISSUE TITLE
Questions: Using data downstream

### ISSUE THREAD

**Issue by lxhunter** [middyjs/middy#1021]
Hi! 

I hope this is okay, i cannot seem to find anything in the documentation regarding setting input data upstream and using it downstream.

Lets say i want to decide upstream which secret to fetch with the secret manager plugin and use that decision downstream.

I can think of a number of ways to do this in writing custom middleware, but i was wondering if there is a best practice?

May the force be with you,
Alex

**Comment by willfarrell** [comment]
"Dynamic" options for core middy middlewares is not supported. Due to the high custom nature everyone will need, it's unlikely we'll support that. Also we default to precaching during cold start which would skip any per-request customization. However, you can easily fork and use one of the existing middlewares as a starting point.

If you'd like to share a middleware you create that enables this with the community, we'd be happy to include it in the community list.
