### ISSUE TITLE
Issues with Latest Version of TypeScript (5.2.2)

### ISSUE THREAD

**Issue by schmalzs** [middyjs/middy#1103]
**Describe the bug**

The latest version of TypeScript (5.2.2) has problems correctly identifying the CommonJS version of Middy that is available in the package.

I've outlined the details of what I am seeing in [this demo repo](https://github.com/schmalzs/middy-ts-demo)

**To Reproduce**

See the [Demo Problem Using This Repo](https://github.com/schmalzs/middy-ts-demo#demo-problem-using-this-repo) section of the README of my repo linked above.

**Expected behaviour**

TypeScript is able to properly identify the CommonJS version of the Middy package that is available.

**Environment (please complete the following information):**

 - Node.js: 18
 - Middy: 4.6.2
 - AWS SDK: N/A

**Additional context**

See details in the README of [this demo repo](I've outlined the details of what I am seeing in [this repo](https://github.com/schmalzs/middy-ts-demo).

The potential fix I outline in the README seems pretty simple -- my suggestion is to introduce an `index.d.cts` type definitions file (note the .cts extension) which seems to give TypeScript the kick in the butt it needs to properly identify the CommonJS version of the package.

Ancillary to this...[others are having issues](https://github.com/microsoft/TypeScript/issues/55705) with building "hybrid" packages with TypeScript 5.2.2. Middy doesn't seem impacted by that though since it's not actually written in TypeScript; instead, it is just helpful by including type definitions 🙂

**Comment by schmalzs** [comment]
Also worth noting that I am happy to PR -- would just want some guidance on how Middy's build process works and how to introduce an `index.d.cts` file into it.

**Comment by willfarrell** [comment]
Thanks for reporting with an example. Since we're planning to drop cjs support in the next version of Middy soon (just waiting on the next lambda runtime to be released ... maybe Nov). We're having enough trouble maintaining one set of types, let alone two. So, I'm going to have to say we're not going to make changes to support this. Sorry.

Two options:
a) lock the version of TypeScript to an older one that works with Middy
b) Report issue to the TypeScript team to resolve on their end
