### ISSUE TITLE
npm packages for plugins

### ISSUE THREAD

**Issue by ehmicky** [middyjs/middy#1246]
**Is your feature request related to a problem? Please describe.**
The [plugins](https://github.com/middyjs/middy/blob/main/plugin) are interesting. However, they are not published to npm at the moment.

**Describe the solution you'd like**
Releasing each plugin under its own npm package.

Thanks for working on Middy! :)

**Comment by willfarrell** [comment]
Thanks for the suggestion. Building on my response to #1245, this was also considered when initially implemented. We chose not to make the packages. Primarily because `core` doesn't allow multiple plugins. And, the purpose of plugins, at the time, was for testing middy itself and for debugging non-production env.

Can you share your use case, maybe a `@middy/plugin-debug` package that includes all plugins has value or alternatively `@middy/plugin-array` to allow plugins to act like middlewares.

**Comment by ehmicky** [comment]
Thanks for your response @willfarrell.

It turns this issue is actually overlapping with #1245, so I'll answer your question there instead. :)
