### ISSUE TITLE
ssm.js imports entire AWS SDK

### ISSUE THREAD

**Issue by thomasedwards** [middyjs/middy#154]
At the moment, the ssm middleware imports the entire AWS SDK.

    const {SSM} = require('aws-sdk')

This weighs a lot. However, you can just ask for the SSM part. For example using `import`:

    import SSM from 'aws-sdk/clients/ssm'

Not sure if you’re thinking of moving to import soon, but this would mean it has to import a lot less code 👍 

Currently at the moment when you require anything from `middy/middlewares`, even if you don’t ask for SSM, it’ll import the entire AWS SDK with it. For example just asking for `jsonBodyParser`, which is 599 bytes (nice), it actually imports about 2.8MB of code.

**Comment by lmammino** [comment]
Hello @thomasedwards and thanks again for using middy and opening an issue.

The `aws-sdk` dependency is already present in the remote lambda runtime available when you publish the lambda, so you don't need to include the lib in your node modules while creating a deployable zip package.

This is the reason why `aws-sdk` is added among`dev-dependencies` (see (here)[https://github.com/middyjs/middy/blob/master/package.json#L46]), so that you can use during tests but should be easier to exclude during the production build phase.

Regarding imports VS require, I would keep middy abstract from those, but I see the advantage in having an ES modules version to support tree shacking where available.

**Comment by thomasedwards** [comment]
> The `aws-sdk` dependency is already present in the remote lambda runtime available when you publish the lambda

Did not know this! Will see how far I can get with it. I’m using Netlify Functions, using their netlify-lambda so not sure how much it’ll moan that the package isn’t installed.

Thanks!

**Comment by lmammino** [comment]
In case you are curious, this is everything you get in the remote environment: https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html 

Regarding netlify, I haven't ever tried it but I'd be curious to know if middy will work with it! One of the long-term goals is to make this project work on other cloud providers

**Comment by DavidWells** [comment]
Middy works on netlify functions 😁 (they are lambda functions under the hood)

Here's an example using some custom JWT auth middleware I wrote https://github.com/DavidWells/meetup-app/blob/master/functions/auth-via-middleware.js

**Comment by lmammino** [comment]
@DavidWells, awesome! I had no idea about that! Also, i like your [custom stuff](https://github.com/DavidWells/meetup-app/blob/master/functions/auth-via-middleware.js#L6)! :D
