### ISSUE TITLE
Separate middy core from middlewares and publish every middleware as separate package

### ISSUE THREAD

**Issue by lmammino** [middyjs/middy#168]
It seems commonly agreed among middy users that it would be much more convenient to split middy core and middy middlewares into separate NPM packages.

This approach is followed by many other projects in the JS community: babel, express, fastify, vuejs, just to name a few...

The obvious advantage is that the user will be able to install only the packages that are strictly needed for his app and thus obtaining smaller lambda artefacts.

I already created a [middy organisation](https://www.npmjs.com/org/middy) on NPM and I feel we should use that to publish the packages. This way the user experience will look like this:

```bash
npm i --save @middy/core @middy/http-normalize-headers @middy/http-error-handler
```

Of course, we will publish in the middy organisation only middlewares that are officially maintained by the middy core team. Other developers can publish third-party middlewares in their own NPM profiles/orgs and we should definitely encourage that.

The main challenge (and most opinionated decision to take) here is *how should we structure the repository (or repositories)*?

I see two possible options:

## 1. Monorepo

This is the approach followed by [babel](https://github.com/babel/babel), and basically it allows to keep all the files in the same repo.

I have never tried to structure a project this way, but my understanding is that, this approach provides the following features:

  1. **1 repository to rule them all** (hence 1 place to file PRs and Issues)
  2. opportunity to standardise tests and settings without having to copy config files in every single repository

(not sure if there are other advantages)

The disadvantage of this approach is that the setup for testing and publishing the individual packages might be very cumbersome. Tools like [lerna](https://github.com/lerna/lerna) might help with this.

## 2. Dedicate GitHub repo per every single NPM package

This is the approach followed by [fastify](https://github.com/fastify).
I would personally feel more confident to go with this approach (just because of previous experience and because is very simple to setup), but I know that it might get out of hand very easily and it might become very hard to ensure consistency across different repositories (babel config, eslint config, circle ci config, etc.)

I would love to put this to votes and maybe have some examples or guidelines, especially if someone here is experienced with option 1.

**Comment by vladgolubev** [comment]
My vote: **Monorepo**

Mostly because of personal struggle to keep >20 GitHub repos for our internal NPM packages at @shelfio groomed and in sync, which resulted in merging them into 1 monorepo managed by Lerna. 

So far 500 PRs and 8 months later, no major hiccups. I won't go deeper into describing benefits of monorepo, they are all typical and well known. But maybe @KnupMan has something special to share

**Comment by vladgolubev** [comment]
Our setup was inspired by [Jest repo](https://github.com/facebook/jest/tree/master/packages).

> The disadvantage of this approach is that the setup for testing and publishing the individual packages might be very cumbersome.

As far as I understand, testing remains the same. Each package (or file with middleware as now) has own tests. Publishing sing Lerna is not much different than just NPM (more similar to [np](https://github.com/sindresorhus/np)), using `independent` mode

Also, [yarn workspaces](https://yarnpkg.com/en/docs/workspaces) is a thing. But that's probably another topic since middy doesn't use yarn?

I'm just afraid to not be in a situation when setting up a GitHub repo / local project for a new middleware can take more time than coding the middleware logic itself 😅

**Comment by dkatavic** [comment]
I don't have experience with Lerna and I don't know the potential problems we are gonna have with it, but as @vladgolubev is experienced with it and is happy with the solution, I am gonna trust him :)

My vote: Monorepo

**Comment by lmammino** [comment]
You (plus reading a bit about lerna and attending a talk about monorepo) definitely convincend me that this is the way to go :) we should try to setup an experimental branch to deal with this!

**Comment by lmammino** [comment]
Closing this one as it's done in the branch [`1.0.0-alpha`](https://github.com/middyjs/middy/tree/1.0.0-alpha), which I believe we should keep as a base branch to develop all the features in this milestone.
