### ISSUE TITLE
Stepping back as main maintainer

### ISSUE THREAD

**Issue by lmammino** [middyjs/middy#263]
Hello all,
I have been realising in these latest days that, unfortunately, I haven't been able to do any meaningful contribution in more than a month.

I also feel that I am probably withholding the evolution of the framework as I might be perceived as the main maintainer (if such role even exists).

I believe we have a pool of amazing skilled people among the current maintainers and I would like to encourage all of you to take over the project and provide direction where you see fit.

Due to my current busy work/life schedule (which I don't envision is going to change much in the near future), I won't be able to commit to the project as much as needed and I don't want to become a bottleneck or to let the project die because of this.

I totally trust all the people on the team to set directions and involve other team members. I am not going to fully step away from the project and I hope I will still be able to do some meaningful contribution in the future, but I can't commit any more to be able to set directions.

The project is still quite small, so I don't think we have to formalize the open source model needed to move things forward, but I am definitely open to conversations. One easy way would be to nominate a project leader, but honestly, I would prefer a more collaborative approach.

Any thoughts?

@acambas @DavidWells @dkatavic @padraigobrien @peterjcaulfield @techfort @theburningmonk @vladgolubev

**Comment by techfort** [comment]
open source fatigue is a real thing @lmammino , sorry for not having been involved much in the last year either. I'd say nominate the person that has been contributing the most as the main maintainer. MIddy is definitely interesting so it deserves some love from those who have time to give it.

**Comment by DavidWells** [comment]
@lmammino thanks everything you have done here thus far! Middy is awesome and I use it all the time! Very much a game changer for the serverless services I have been writing.

I think middy addresses a real need in the serverless world (sharing common middlewares, keeping handlers focused on clean business logic, & foreshadowing AWS announcements like `layers` 😜).

I'm interesting in seeing the project move forward and would be happy to help with some of the burden.

I saw the v1 branch with the mono-repo refresh. The idea there was working towards https://github.com/middyjs/middy/issues/159 right? What was the status of that and how can I help?

**Comment by lmammino** [comment]
Thanks for the nice words @techfort and @DavidWells! Really appreciated ☺️
Everything I envisioned for V1 is currently tracked as [a milestone](https://github.com/middyjs/middy/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0.0).

Of course, also this milestone is definitely open for discussion and can be changed.

**Comment by peterjcaulfield** [comment]
Hey sorry for the delayed response @lmammino . Like @techfort I haven't been involved much since middy became open source and would like to thank you for all your efforts as well as everyone else who has contributed to getting middy where it is today. Considering this and the fact that I am not really working with AWS Lambda at present, I don't have strong opinions and would rather delegate to those who have been more active in the project in the past year (@DavidWells, @vladgolubev, @theburningmonk) and yourself to best determine its future. Whatever decision, I believe that future is bright :)

**Comment by theburningmonk** [comment]
Hey @lmammino thanks a lot for all your hard work on middy, it's provided a lot of values to many of us and addresses a real need in this space! I'm also keen to move v1 branch forward as well, as the mono package is holding quite a few people back. Of the open items on the milestone #169 seems to need a bit more thought and in the interest of getting v1 out do you mind bumping #169 as a future improvement (maybe as an item v1.1)?

I should have more time after the new year, and since DAZN actually uses middy quite a bit I'm also happy to push our guys to do more in terms of contributions :-P

**Comment by dkatavic** [comment]
Thanks for all the contribution @lmammino , you did an amazing job with middy

**Comment by vladgolubev** [comment]
Thanks for making middy happen @lmammino! It helps us at @shelfio tremendously! Since we have at least >100 Lambdas using middy - I will be contributing to this project for some time as well. I hope to dedicate some quality time around Christmas holidays. I'd like to finally publish 1.0 with monorepo setup as well.

**Comment by lmammino** [comment]
Great to hear middy is used in real-world apps :) maybe at some point, we can have a section "companies/projects using middy" in the official website!

Thanks also to @peterjcaulfield, @theburningmonk, @dkatavic and @vladgolubev for nice words!

Regarding #169, i am happy to reschedule that for a feature release!

**Comment by dbartholomae** [comment]
I would be interested in helping as we might heavily rely on this middleware for our upcoming software projects. I just finished a [jwt auth middy middleware](https://github.com/dbartholomae/middy-middleware-jwt-auth) if you are interested in my code style and experience with the framework :)

**Comment by lmammino** [comment]
Hello @dbartholomae, and thanks for your kind message.

Everyone is welcome in middy, so feel free to start contributing to the open issues or to suggest new features.

In my view, the main focus would be to be able to release v1.0.0 so  that we can have a more modular engine and also we can deprecate v0.x which is currently forcing us to replicate some of the changes in 2 branches with 2 different codebases.

Regarding your middleware, it seems really cool. We should add it to the list of 3rd party middlewares in the readme :)

**Comment by dbartholomae** [comment]
Thanks! I assume this is the best place to start when thinking about how to best contribute to 1.0.0?
https://github.com/middyjs/middy/milestone/2
