### ISSUE TITLE
"middify" express/koa middleware

### ISSUE THREAD

**Issue by techfort** [middyjs/middy#31]
Not an issue as much as something we could think of to re-use some of the fantastic work that already exists in the OSS world.
We could create a middify() function that takes any express/koa middleware and makes it lambda compatible, not sure about implementation details, but it should just be a matter of translating the `(req, res, next) => {}` format into `(handler, next) => {}` or something.. cc @lmammino

**Comment by lmammino** [comment]
It sounds as a very good idea, though it might not be super simple because of the different abstractions: request/event -> response. So the first issue would be to find a way to remap the data across them.

This repo might be a good starting point to figure out how to address this issue: https://github.com/awslabs/aws-serverless-express

**Comment by trongdong** [comment]
I saw the same idea already implemented in this repository: https://github.com/dougmoscrop/serverless-http   
I was thinking about this at first, but then I realize that I prefer lean code base that fit to serverless/ lambda environment rather then reuse the existing middleware.

**Comment by willfarrell** [comment]
@techfort was there a specific middleware you needed to use?

**Comment by TAnas0** [comment]
If I understand correctly what you guys are trying to achieve, then this would help also support Zeit Now serverless NodeJS functions (https://zeit.co/blog/now-node-helpers).

I wanted to refactor my crude middlewares into Middy, but the handler has a different signature.
