### ISSUE TITLE
New logo for Middy

### ISSUE THREAD

**Issue by lmammino** [middyjs/middy#375]
I was thinking to have a new logo once 1.0.0 is finally released.

This is what I came up with lately. What do you think? I am super happy to consider other proposals if anyone wants to try to submit one! :)

![middy](https://user-images.githubusercontent.com/205629/62822853-15a7bb00-bb81-11e9-9aad-f407e3f0ae09.png)

**Comment by MaxVinogradov** [comment]
@lmammino Looks Cool! 
Maybe it will be good to mention AWS Lambda in logo =)?
Like inverted lambda symbol instead of the last "y" in "middy" word.
Just idea, nothing more...

**Comment by lmammino** [comment]
Hello @MaxVinogradov, I like the idea in itself, but at the moment I cannot picture anything decent with that in my head :D Also I am thinking something more cartoonish, maybe something in between the current logo and something like [kore](https://kore.io).

I think I might need to hire a logo designer or an illustrator :P

**Comment by willfarrell** [comment]
I like the current logo, plus it comes with an emoji.

**Comment by brettstack** [comment]
Love this logo. Adding Lambda logo in there will definitely help with recognition. The immediate thing I can think of is adding it to the middle of the hexagon.

Alternative idea: similar to what you have, but instead of hexagon inside a hexagon inside a hexagon, we have lambda logo inside lambda logo inside lambda logo (with alternating colors like you have). Though maybe I'd hate it after seeing it 😅
