### ISSUE TITLE
Custom Validator Error Messages

### ISSUE THREAD

**Issue by baileytincher** [middyjs/middy#424]
I wanted to intercept errors thrown by middy/validator to provide a more user-friendly response. Things like checking what fields failed and then telling them in English what they need to fix. This is rather specific to an individual use case, but would you be interested in a PR for something more general? Like the ability to pass in an error handler function as one of the config options?

**Comment by lmammino** [comment]
Hello @baileytincher! Thanks a lot for reaching out :)

Did you consider implementing an additional (bespoke) error handler middleware that can be attached in the pipeline after the validator so that you can intercept the errors coming from there and change the returned response before it gets back to the client?

If you did, is there anything missing in the current implementation that stops you from going with this approach?

The reasono why I am asking this is that i would like to keep official middlewares as simple as possible and enable customisation more through composition with bespoke middlewares rather than through more configuration.

**Comment by baileytincher** [comment]
Great idea, I didn't think about that! Do you have any tips on how I can make it not step on the toes of `http-error-handler`? I know that if I order the middlewares properly I can circumvent that issue by ordering the middleware's properly, but I was wondering if there was a more robust solution?

Alternatively, I could just add a special case to the `http-error-handler` middleware for my own purposes, but I imagine that may be more impactful than some others would want if they were to want to reuse it.

**Comment by lmammino** [comment]
Middleware ordering and early returns is the way to go imho. That's generally the tradeoff with middleware frameworks, everything is very composable, but order matters and you have to be careful in some circumstances.

> Alternatively, I could just add a special case to the http-error-handler middleware for my own purposes, but I imagine that may be more impactful than some others would want if they were to want to reuse it.

Again I would prefer composition to overcomplicated middlewares, especially for the core ones. As an alternative you might create your own custom `http-error-handler` as a fork of the current one and all your custom logic there.

**Comment by willfarrell** [comment]
There is an even easier and cleaner way. Check out https://github.com/epoberezkin/ajv-errors then use a fork of the validator middleware adding in the hook.

```
var Ajv = require('ajv');
var ajv = new Ajv({allErrors: true, jsonPointers: true});
// Ajv options allErrors and jsonPointers are required
require('ajv-errors')(ajv /*, {singleError: true} */);
```
