### ISSUE TITLE
ssm middleware caches errors

### ISSUE THREAD

**Issue by theburningmonk** [middyjs/middy#660]
What are the steps to reproduce this issue?
-------------------------------------------
1. use the `ssm` middleware to fetch data from a SSM parameter that doesn't exist, with caching set to `true`
2. the function errors with `InvalidParameter` as expected
3. add the parameter
4. the function still errors with `InvalidParameter`

What happens?
-------------
The error response is cached.

Only after the cache expiration or deployment is this error cleared.

What were you expecting to happen?
----------------------------------
`InvalidParameter` is cleared after adding the missing parameter.

What versions of software are you using?
----------------------------------------
**Node.js Version:** 14.15.2

**Middy Version:** 2.0.1

**AWS SDK Version:** 2.892.0

**Comment by willfarrell** [comment]
The request promise is cached and has no idea if it's a valid response. Sound like we might need to add a hook to catch when error happen during the promise resolve to force a re-fetch on the next path. Thanks for reporting.

**Comment by willfarrell** [comment]
PR #662 added. Let me know what you think.

**Comment by theburningmonk** [comment]
If I understood the change correctly, it'll clear the cache on error during an update, which means you'll lose any previously cached value, right?

That'll be undesirable, because the cached value is likely still good, and just because we can't get an update, we shouldn't delete the previously cached value.

The desired behaviour (for me at least) during an error is:
* if there is a cached (stale) value already, then keep using the cached value and swallow the exception, but make sure that the next invocation would try to update again
* if there isn't a cached value already then there's nothing you can do, just throw an exception

**Comment by theburningmonk** [comment]
btw, I believe the behaviour I described is how it used to work for the SSM and SecretManager middlewares in 0.x and 1.x
https://github.com/middyjs/middy/blob/1.x/packages/ssm/index.js#L92-L100

**Comment by willfarrell** [comment]
That is right, and I did think about that. Since we're doing a batch request, all the successful ones would be requested again anyway so it doesn't matter too much. One could, as you've shown, break up their ssm requests into multiple middlewares to accomplish this. Of course, you would only want to assign to the context once to prevent running this synchronously (I'll add an example on how to do this to the docs). I would hope these types of errors are resolved during testing before making their way to production.

I'll continue to reflect on this, see if an idea pops to mind on how to accomplish this without the excess complexity and performance implications.

**Comment by willfarrell** [comment]
I think I found a clean way to do it. See PR #662 for details.
