### ISSUE TITLE
Why does @middy/http-error-handler not expose error 500 by default?

### ISSUE THREAD

**Issue by TPME** [middyjs/middy#690]
What are the steps to reproduce this issue?
-------------------------------------------
```
throw new createHttpError.InternalServerError();
```

What happens?
-------------
Lambda returns a status 200

What were you expecting to happen?
----------------------------------
Lambda throws an error 500

Any other comments?
-------------------
Why is this happening? I would expect Lambda to throw an error 500.

What versions of software are you using?
----------------------------------------
**Middy Version:** 2.4.2

**Comment by willfarrell** [comment]
Generally, you don't want to return internal errors because they can leak information about your system. This is the default for `http-errors`. It does allow you to override when it's intentional.

See this unit test for example on how to use expose: https://github.com/middyjs/middy/blob/main/packages/http-error-handler/__tests__/index.js#L180

When using `InternalServerError` the status code in the response should be 500. Are you saying it's 200?

**Comment by TPME** [comment]
I can get it working, and now I understand what the thought behind the different options are, but it was a bit hard to understand at first from the documentation.

Nevertheless, the following remains:

1) About your comment "When using InternalServerError the status code in the response should be 500. Are you saying it's 200?" Yes, that's what's happening (not using expose nor setting `fallbackMessage`). I would expect that even without using expose, it would tell the requester that there was an internal error (500).

2) If setting `fallbackMessage` to a string, it correctly enables the 500 errors to be shown, however it does nowhere use the `fallbackMessage` (no message is sent as a response).

**Comment by willfarrell** [comment]
Thanks for digging into this more. I'll update the docs to hopefully make it a little clearer of others

https://github.com/middyjs/middy/blob/main/packages/http-error-handler/__tests__/index.js#L180https://github.com/middyjs/middy/blob/main/packages/http-error-handler/__tests__/index.js#L159
