### ISSUE TITLE
AJV-Keywords Support

### ISSUE THREAD

**Issue by ayushsharma82** [middyjs/middy#698]
Hi,

Thanks for developing an amazing framework.

I was using middy@1.4.0 in a couple of my projects and `ajv-keywords` was very helpful in middy validator.

With the switch to v2, It got removed from the validator. ( Package size is not a concern for me ), Now, this has rendered my whole code incompatible with the changes made to the validator package and _I can't seem to find any documentation in middy to add additional plugins to validator(Ajv)_.

If somebody can shine a light on this issue: Please add some level of documentation to install `ajv-keywords` in v2, so that upgraders don't face any issues.

Regards,
Ayush

**Comment by willfarrell** [comment]
Hi thanks for you question.

You are correct `ajv-keywords` was removed, along with `ajv-errors`, partly due to package size. There were other factors that came into consideration. I v2 we made sure there was still a mechanism to included them is needed. You can pass in a compiled ajv object instead of a json schema. Alternatively there is: [`middy-ajv`](https://www.npmjs.com/package/middy-ajv) which move everything to a build.

Here is an example how to do compile the json schema: https://ajv.js.org/guide/getting-started.html#basic-data-validation
You would then pass in the `validate` variable as inputSchema or outputSchema.

An example covering this case would be a great addition to the docs. Would you like to open a PR to add it?
