### ISSUE TITLE
SSM middleware `ssm.InvalidParameter` errors can not be caught

### ISSUE THREAD

**Issue by BobD** [middyjs/middy#763]
I would like to ask if it is possible to gracefully handle SSM errors which are fired when the supplied `fetchData` paths are not correct.

What are the steps to reproduce this issue?
-------------------------------------------
```
import middy from "@middy/core";
import ssm from "@middy/ssm";

const baseHandler = async event => event;
const handler = middy(baseHandler);

handler
  .use(
    ssm({
      fetchData: { redirects: "/some/non/existing/ssm" },
    })
  )

module.exports = { handler };
```

What happens?
-------------
An `ssm.InvalidParameter` error is thrown which does not seem be caught using a `onError` function in a following middleware which uses the values from the SSM 

What were you expecting to happen?
----------------------------------
The `onError` being able to catch the `ssm.InvalidParameter` so this error can be handled gracefully.

Or the option to pass default values to the `ssm` middleware which would prevent the `ssm.InvalidParameter` from being fired.

Any logs, error output, etc?
----------------------------
`Error: ["ssm.InvalidParameter ...    at Object.getInternal (/var/task/node_modules/@middy/util    at processTicksAndRejections (internal/process/task_queue    at async applyPageRedirectsBefore (/var/task/services/pag    at async runMiddlewares (/var/task/node_modules/@middy/co    at async runRequest (/var/task/node_modules/@middy/core/index.js:80:5)`

What versions of software are you using?
----------------------------------------
**Node.js Version:** 8.1.0

**Middy Version:** 2.5.4

**AWS SDK Version:** None specified, only using Middy middlewares

**Comment by willfarrell** [comment]
We have a test for this specifically: https://github.com/middyjs/middy/blob/main/packages/ssm/__tests__/index.js#L393, the `Error` is being passed to `onError`. You can test this by adding in `.onError(request => console.log)` to your middleware stack.

The error you show is the expected error form a `Promise.allSettled()` (which is how getInternal resolves all requests). How would you imagine the error to be returned to allow it to be more graceful? Maybe something like: https://github.com/middyjs/middy/pull/762#issuecomment-997437940 and have `originalErrors` as part of the `Error` object? FYI You can see the specific errors by inspecting `request.internal`.

There are no plans to add in the functionality to allow default fallbacks at this time due to the increased complexity it adds in. If you'd like to create and share a middleware that can, I'd be happy to include it in the community middleware list.

**Comment by BobD** [comment]
Thanks for the detailed feedback. For some my former approach did not work using a `onError` handler inside the custom middleware which was using the SSM paramater values. This approach now seems to work:

```
import middy from "@middy/core";
import { getInternal } from "@middy/util";
import { CloudFrontRequestEvent, CloudFrontRequestResult } from "aws-lambda";

type ApplyPageRedirects = middy.MiddlewareObj<CloudFrontRequestEvent, CloudFrontRequestResult>;
type ApplyPageRedirectsBefore = middy.MiddlewareFn<CloudFrontRequestEvent, CloudFrontRequestResult>;

const getRedirectsFromParamStore = ({ redirects = "" }: { redirects?: string } = {}) => {
 ...
};

export const applyPageRedirects = (): ApplyPageRedirects => {
  const applyPageRedirectsBefore: ApplyPageRedirectsBefore = async request => {
    const requestSSMData = await getInternal(["redirects"], request);
    const redirects = getRedirectsFromParamStore(requestSSMData);
    const redirectRegex = new RegExp(Object.keys(redirects).join("|"), "gi");
    const redirectUrls = request.event.Records[0].cf.request.uri.match(redirectRegex);

    if (redirectUrls && redirectUrls.length) {
      request.event.Records[0].cf.request.uri = redirects[redirectUrls[0]];
    }
  };

  return {
    before: applyPageRedirectsBefore,
    onError: async request => {
      console.error("SSM parameter store is not available");

      return request.event.Records[0].cf.request;
    },
  };
};
```

I'll try and see why it did not work before, and otherwise fetch my stupid hat..
