### ISSUE TITLE
Provide after type for each middleware

### ISSUE THREAD

**Issue by winston0410** [middyjs/middy#828]
**Is your feature request related to a problem? Please describe.**
Right now there is no explicit type that describes the transformed event and context after applying middlewares.

For example, originally `event.body` is `string`, but after applying `[@middy/http-json-body-parser](https://www.npmjs.com/package/@middy/http-json-body-parser)`, it will become `object`. But the type returned is still [`APIGatewayProxyEventV2`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a1260a1f3d40f239b53fd29effba594b0d1bee08/types/aws-lambda/trigger/api-gateway-proxy.d.ts#L218)

```javascript
const handler = middy((event) => {
  const obj = {...event.body, hello: "foo"} //Typescript will complain this, as it still thinks event.body is string and it cannot be spreaded
  // more
}).
use(jsonBodyParser())
```

**Describe the solution you'd like**
Each package should export a type to describe the change after transformation

**Describe alternatives you've considered**
To create a type by the user, but a unified type provided by the community will surely be better.

**Additional context**

**Comment by willfarrell** [comment]
Because the whole point of Middy is to mutate types, setting types can tricky. In your example the resulting type could be an object, but easily could be whatever the input is if Middy fails to parse out an object.

We're open to a PR that improves types if you'd like to put one together. I know others have looked into this in the past and commented on that it may not be possible with how @middy/core is setup.
