### ISSUE TITLE
Cannot use import statement outside a module - Middy 3.0.4 w/ Jest, TypeScript

### ISSUE THREAD

**Issue by tylerzisk** [middyjs/middy#850]
**Describe the bug**
Cannot run Jest tests with any versions of Middy above 3.x, as imports are not resolving for Middy dependencies. I have attempted using `babel-jest` to resolve `.js` dependencies with the same issue. This is a Serverless framework app with about 13 TypeScript functions we deploy to individual Lambdas to AWS.

What is also strange is that the functions will build fine with Serverless framework for deployments. It seems to be only tests that cannot parse import statements correctly.

Error mesage:
![Screen Shot 2022-06-07 at 11 42 09 AM](https://user-images.githubusercontent.com/18252118/172447924-60f5db9d-e7b5-43a6-8a68-1334df7ca5a7.png)

**Environment (please complete the following information):**

Dev dependencies
- Node.js: [14.16.1]
- TypeScript [^4.7.2]
- @middy/core [3.0.4]
- @middy/http-cors: [3.0.4]
- @middy/http-error-handler": [3.0.4]
- @middy/http-json-body-parser": [3.0.4]
- @middy/http-response-serializer": [3.0.4]
- @middy/validator": [3.0.4]

Test dependencies
- Jest [^26.6.3]
- TS-Jest [^26.5.6]

jest.config.js:
```
module.exports = {
  collectCoverage: true,
  coverageDirectory: "jest-coverage",
  moduleFileExtensions: ["js", "ts", "json", "node"],
  modulePaths: ["<rootDir>"],
  testMatch: ["**/*.spec.ts"],
  transform: {
    "^.+\\.ts?$": "ts-jest",
  },
  verbose: true,
  testEnvironment: 'node'
};
```

tsconfig.json
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "esModuleInterop": true,
    "preserveConstEnums": true,
    "strictNullChecks": true,
    "sourceMap": true,
    "allowJs": false,
    "target": "es6",
    "typeRoots": ["node_modules/@types"],
    "resolveJsonModule": true,
    "moduleResolution": "node"
  }
}
```

**Comment by willfarrell** [comment]
This sounds like a config issue, seeing how it bundles fine for deployment. In v3 we added support for both cjs and esm depending on how you include middy. Some webpack users are also running into this issue, I wonder if the same resolution could be applied here. As more dependencies start to support esm, I expect this to come up more often across the board.

A work around that might work could be to use the CommonJS file: `import middy from '@middy/core/index.cjs'`

I've started putting together sample config files for bundling, https://middy.js.org/docs/best-practices/bundling, `ts` has not been included yet. A PR would be welcome once someone finds a solution.

**Comment by tylerzisk** [comment]
Changing the imports to use the `.cjs` extension does not work either. I applied the `/index.cjs` to all of the middy dependencies being imported. 

![Screen Shot 2022-06-10 at 9 29 36 AM](https://user-images.githubusercontent.com/18252118/173099546-325e3e87-5107-4e9a-b6f0-6a33306984bf.png)

**Comment by willfarrell** [comment]
Thanks for testing. Do you have a babel config file? The error mentions jest uses babel to transpile. https://middy.js.org/docs/best-practices/bundling/#babel

**Comment by tylerzisk** [comment]
Yeah I tried those configurations listed above, also tried some StackOverflow articles about using `babel-jest`, but no dice on either solution.

**Comment by willfarrell** [comment]
Sorry, I'm out of ideas at this point.

**Comment by willfarrell** [comment]
Has this been reported to https://github.com/kulshekhar/ts-jest/issues? Curious if they have any ideas? I doubt middy is the first to ship esm packages.

**Comment by Muthuveerappanv** [comment]
I may have found a solution for this. Let me know if it works

1. Update **jest.confing.ts** with the below
``` json
extensionsToTreatAsEsm: [".ts"],
  globals: {
    "ts-jest": {
      "useESM": true
    }
  },
  ```
2. Add the following to the **npm test script** `"jest": "NODE_OPTIONS='--experimental-vm-modules' jest"`
3. Jest has to be imported from globals post this `import {jest} from '@jest/globals'` (works previously without importing)

@willfarrell  - 'i doubt middy is the first to ship esm packages' triggered me to start finding answers in the respective repos

**Reference:**
https://github.com/facebook/jest/issues/10822
https://github.com/microsoft/vscode/issues/77871
https://stackoverflow.com/questions/65190123/referenceerror-jest-is-not-defined-when-running-unit-test

**Comment by Ben-Donnelly** [comment]
> I may have found a solution for this. Let me know if it works
> 1. Add the following to the **npm test script** `"jest": "NODE_OPTIONS='--experimental-vm-modules' jest"`
> 2. Update **jest.confing.ts** with the below
> ``` json
> extensionsToTreatAsEsm: [".ts"],
>   globals: {
>     "ts-jest": {
>       "useESM": true
>     }
>   },
>   ```
> 3. Jest has to be imported from globals post this `import {jest} from '@jest/globals'` (works previously without importing)
> 
> @willfarrell  - 'i doubt middy is the first to ship esm packages' triggered me to start finding answers in the respective repos
> 
> **Reference:**
> https://github.com/facebook/jest/issues/10822
> https://stackoverflow.com/questions/68520619/jest-typescript-with-es-module-in-node-modules-error-must-use-import-to-load-e
> https://stackoverflow.com/questions/65190123/referenceerror-jest-is-not-defined-when-running-unit-test
> 

Unfortunately I am not in a position to use this solution.

**Comment by ecdavis** [comment]
Ran into the same issue with a similar stack (Node, TypeScript, Serverless, middy 3, Jest, ts-jest).

The root of the problem seems to be that jest/ts-jest will transform your code in to commonjs-compatible JS before running your tests. By default, anything in `node_modules` will _not_ be transformed. So if you're importing ESM-compatible JS from `node_modules` you'll get this SyntaxError.

A simple solution is to set Jest's [`moduleFileExtensions` option](https://jestjs.io/docs/configuration#modulefileextensions-arraystring) to prefer `cjs` over `js` file extensions, e.g.:
```
moduleFileExtensions: ["cjs", "js", "mjs", "jsx", "ts", "tsx", "json", "node"],
```

I don't know if this is necessarily the best, but the other options (start using Babel, convert project to ESM) were cans of worms I didn't want to open. @tylerzisk @Ben-Donnelly maybe this works for you?

Some links I found helpful:
- Jest's transform step ignores the contents of `node_modules` by default: https://jestjs.io/docs/configuration#transformignorepatterns-arraystring
- ts-jest guide to transforming a module in `node_modules` -- you have to configure Jest to _not_ ignore a particular module: https://github.com/kulshekhar/ts-jest/blob/main/TROUBLESHOOTING.md#transform-node-module-explicitly
  - But be aware that ts-jest does not use Babel by default, so you need to enable it:  https://kulshekhar.github.io/ts-jest/docs/getting-started/options/babelConfig/
- Also ran into this weird issue which convinced me to stop pursuing the Babel transform option: https://github.com/facebook/jest/issues/6229#issuecomment-420170801

**Comment by willfarrell** [comment]
Thanks everyone for sharing their detailed investigation. Sounds like there is a consensus that this is a `jest` / CI configuration issue. If someone would like to open a PR to document a solution, I'd be open to it.

**Comment by ecdavis** [comment]
@willfarrell I will add that I don't have to work around this issue for other packages like the AWS SDK, which supports both CommonJS and ESM. Might be some way to configure middy's packaging to make this smoother?

Comparing:
https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/package.json#L17
and
https://github.com/middyjs/middy/blob/main/packages/http-error-handler/package.json#L13

But I know next to nothing about JS packaging so 🤷

**Comment by willfarrell** [comment]
I feel like there is no winning with this one. 

The TypeScript community wants something like this: https://gist.github.com/cef62/a14c3003095fe56fba2b69d6c57e5777?permalink_comment_id=4183778#gistcomment-4183778 while AWS is using the backwards compatible notation for older version of NodeJS (<=nodejs12.x), likely because they still have to support them. Both on complete opposites.

I opted to go with what the NodeJS documentation recommended as best practice for the lowest version we support (>= nodejs14.x). https://nodejs.org/docs/latest-v14.x/api/packages.html#packages_conditional_exports

I've gone ahead and documented working configurations for the most popular transpilers and bundlers (https://middy.js.org/docs/best-practices/bundling). If a build tool isn't keeping up to date the community will need to help them update or switch to another tool.

Personally, I use `rollup` & `esbuild` and haven't had an issue yet in my transition to fully ESM.

**Comment by rodrigommv1987** [comment]
I had this same issue yesterday, and was able to sort it out by setting in jest's config key [moduleFileExtensions](https://jestjs.io/es-ES/docs/configuration#modulefileextensions-arraystring) `cjs` as first element of the array, like this:

`{
  "moduleFileExtensions": [
    "cjs",
    "js"
  ],
  ...
}`

With that, the tests that uses middy are passing fine now. 
Hope it helps.

**Comment by tylerzisk** [comment]
After attempting the `moduleFileExtensions` fix above, I now run into a timeout error from Middy: 

<img width="701" alt="Screen Shot 2022-06-17 at 10 34 06 AM" src="https://user-images.githubusercontent.com/18252118/174339859-c53472d2-13fe-44bb-876e-acc00dec576e.png">

**Comment by willfarrell** [comment]
I've released `3.1.0-rc.0` that now includes `main` and TS 4.7+ support. Let me know if it's better or worse.

**Comment by willfarrell** [comment]
Thanks for sharing!

You can alternatively remove `getRemainingTimeInMillis` or set `timeoutEarlyInMillis` to `0`

**Comment by alexbruno** [comment]
December 2024. I'm facing this issue.
Does anyone have any insight about it?

**Comment by JenniferJarnstrom** [comment]
set version to 4.7.0 which matches my middy core. This resolved my issue.
