### ISSUE TITLE
Failed to import middy in typescript+CJS

### ISSUE THREAD

**Issue by Holi0317** [middyjs/middy#886]
**Describe the bug**

Middy is not exporting properly in CJS.

**To Reproduce**

In a typescript project with `module == commonjs` in compiler config, import middy with:

```ts
import middy from '@middy/core'
```

This will pass the typecheck. However in runtime, following error will throw:

```
TypeError: (0 , core_1.default) is not a function
```

Tracing the compiled code shows that ts is trying to do `const middy = require("@middy/core").default` instead of `const middy = require("@middy/core")`

I can "hack" around typescript by `import * as middy from "@middy/core"`. But then I lose all the type information.

**Expected behaviour**

Importing should work in typescript/compiled code in CJS.

**Environment (please complete the following information):**
 - Node.js: 14
 - Middy: 3.2.0

**Additional context**

In middy's build system, there is a line trying to fix CJS export: https://github.com/middyjs/middy/blob/979f81bd6da7788a18abf6c32172867654fc3ab6/.github/workflows/release.yml#L39

If this line is removed, importing should work. But that is a breaking change for all CJS users as .

Alternative solution is to export all the symbols with named export. The import should then work in both CJS and ESM environment.

**Comment by willfarrell** [comment]
Middy ships with 2 versions of the code; CJS and ESM, both transpiled to NodeJS 14 (for v3). NodeJS automatically chooses based on the import method used as described in the exports (see module package.json). Because two versions are shipped, there is no need to ship export polyfills with CJS (typically a common pattern for modules used both in NodeJS and the browser).

This feels like a compiler config issue. Have you tried enabling bundling into one file? This step should happen first, allowing the native imports to work as expected before transpiling to CJS notation. There was some discussing back in May around building for jest that might help.

Otherwise `import * as middy from "@middy/core"` will be my recommendation. Might be worth opening an issue with the the TS community to get types import support for this notation.

**Comment by tinemlakar** [comment]
I have the same issue as @Holi0317  on @midy/core@3.3.1.
 I don't see why that would be an issue with config - all other packages are working fine.

**Comment by Holi0317** [comment]
I ended up halting and re-evaluation integration with middy in my project. Currently I have the following solutions for integrating middy:

1. Migrate my project to `type: module` -- Not an options for us as it breaks APM instrumentation. Plus ESM is a mess in node right now
2. `// @ts-expect-error` -- Not an option
3. Add `serverless-webpack` to our project -- We currently not using it
4. Vendor/fork middy core with proper exports -- Which is like the most viable solution as we are not planning to use other middlewares and the core is in fact very small

**Comment by tinemlakar** [comment]
The issue seems to be resolved if you add `"esModuleInterop": true` to your tsconfig.json, however that may cause issues elsewhere.
