### ISSUE TITLE
Support aws-sdk-v3 with secret-manager middleware

### ISSUE THREAD

**Issue by jarpz** [middyjs/middy#904]
**Is your feature request related to a problem? Please describe.**
When we use secret-manager middleware, it just support v2 aws-sdk. Also exclude code doesn't work:

`    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        External:
          - aws-sdk/clients/secretsmanager.js
        EntryPoints:
          - app.ts`

Error: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: ✘ [ERROR] Could not resolve "aws-sdk/clients/secretsmanager.js"

    node_modules/@middy/secrets-manager/index.js:2:27:
      2 │ import SecretsManager from 'aws-sdk/clients/secretsmanager.js';

**Describe the solution you'd like**
Use secret-manager middleware with @aws-sdk/client-secrets-manager": "^3.171.0

Regards

**Comment by willfarrell** [comment]
1. Updating to AWS SDK v3 is planned for Middy v4. I hope to start work on it before the end of the year. When AWS plans to release nodeJS v18 runtime is a factor for the release of v4. Please reach out to your AWS rep to let them know this is important to you and to share detail publicly.
2. `Could not resolve "aws-sdk/clients/secretsmanager.js`, `aws-sdk` is a devDependency that you will need to install for running your own unit test. It's included in the lambda runtime, which is why it's not a required dependency.

**Comment by jarpz** [comment]
> 1. Updating to AWS SDK v3 is planned for Middy v4. I hope to start work on it before the end of the year. When AWS plans to release nodeJS v18 runtime is a factor for the release of v4. Please reach out to your AWS rep to let them know this is important to you and to share detail publicly.
> 2. `Could not resolve "aws-sdk/clients/secretsmanager.js`, `aws-sdk` is a devDependency that you will need to install for running your own unit test. It's included in the lambda runtime, which is why it's not a required dependency.

I got it...

Any workaround that we can use?

Maybe override some methods?

Regards

**Comment by willfarrell** [comment]
For `2.` `npm i -D aws-sdk` should do the trick. As for using SDK v3, none that I know of.
