### ISSUE TITLE
Adds possibility to fetch also ssm parameter versions

### ISSUE THREAD

**Issue by Bart1909** [middyjs/middy#915]
It would be nice, if there is an additional parameter to fetch also ssm parameter versions.
Maybe, it could be possible to enter the amount of versions, you want to fetch. These could be stored for example as `context['parameter1_versions'][0]`

**Comment by willfarrell** [comment]
That uses the `GetParameterHistoryCommand` I believe and would require fetching each key individually. This can lead to rate limiting issues (early version of middy had this issue), which is why the current implementation uses batching. I could see this as it's own middleware, where it only fetches one or two. I'm not sure it's a good fit for the core middlewares though, however, happy to have it included in the community list. I'm curious what the use case if for this suggested feature.

**Comment by Bart1909** [comment]
This should also work with the used `getParameters` command. You can append `:VersionNumber` and retrieve a version.
But it would result in an additional call, because you would first have to retrieve the current version (which is returned, when you get the latest value) and then you can fetch the xx versions before.
Our use case is the following:
We store rotating keys as ssm parameters and want to give a hint, if an old value is used.
