### ISSUE TITLE
validator should raise error also when non expected extra properties are received

### ISSUE THREAD

**Issue by marcodali** [middyjs/middy#936]
**Describe the bug**
Validator package does an excellent job by throwing errors when a required property is not present in the request.body but it should also validate / not allow the body to have extra properties

**To Reproduce**
How to reproduce the behaviour: add an extra property in the json body of a POST request to create a new resource. The extra-property is not validated and as a result it could be added as a new property in a document based DB like mongoDB or DynamoDB

**Expected behaviour**
Instead of "Event object failed validation", message: "must have required property category" maybe an error like "not expected extra property category2 not supported"

**Environment (please complete the following information):**
 - Node.js: [16]
 - Middy: [3.6.2]
 - AWS SDK [2.4.21]

**Additional context**
I'm talking about the input schema validator middleware .use(validator({ inputSchema }))

**Comment by willfarrell** [comment]
This is not a middy issue, the error messages are from ajv. You can suggest the change in ajv, but I don't expect it would be accepted as I believe the messages are from the JSON Schema spec. However, in v4 of Middy I've made it so that all error messages can be overridden more easily for translation purposes and added in multi-lang `errorMessage` support. This new functionality should allow you to accomplish what you'd like to do.
