### ISSUE TITLE
Using SSM with Lambda Power Tools Tracer

### ISSUE THREAD

**Issue by marcioemiranda** [middyjs/middy#948]
**Describe the bug**
ssm middleware failing when using with Lambda Power Tools

**To Reproduce**
The source code in the lambda handler sets up Lambda Power Tools using middy. Everything works fine until I include ssm middleware (plus the "before" hook). The goal is to populate a global variable with the contents of a SSM parameter and use cache to keep it for several minutes.

```
import { injectLambdaContext } from "@aws-lambda-powertools/logger";
import { logMetrics, MetricUnits } from "@aws-lambda-powertools/metrics";
import { captureLambdaHandler } from "@aws-lambda-powertools/tracer";
import middy from "@middy/core";
import jsonBodyParser from "@middy/http-json-body-parser";
import validator from "@middy/validator";
import httpErrorHandler from "@middy/http-error-handler";
import ssm from '@middy/ssm';
import { APIGatewayProxyEvent, APIGatewayProxyResult, Context } from "aws-lambda";
import { logger, metrics, tracer } from "../aws/powertools";
import { sessionSchema } from "./schema";

const lambdaHandler = async (
  event: Event<SessionInfo>, context: Context
): Promise<APIGatewayProxyResult> => {

  console.log(`Context: ${JSON.stringify(context, null, 2)}`);

    return createResponse(200, {
      message: "success",
    });
  } catch (error) {
    logger.error("Unexpected error processing POST session.", error as Error);
    return createResponse(500, {
      message: String(error),
    });
  }
};

const handler = middy(lambdaHandler)
  .use(captureLambdaHandler(tracer))
  .use(logMetrics(metrics, { captureColdStartMetric: true }))
  .use(injectLambdaContext(logger, { clearState: true }))
  .use(jsonBodyParser())
  .use(
    validator({
      inputSchema: sessionSchema,
    })
  )
  .use(httpErrorHandler())
  .use(
    ssm({
      fetchData: {
        qosParams: process.env["SSM_PARAMETER_NAME"] || "/qos/endpoints",
      },
      cacheExpiry: 15 * 60 * 1000,
      setToContext: true,
    })
  )
  .before((request: any) => {
    //qosParams = request.context.qosParams;
    //console.log(qosParams);
    console.log("BEFORE");
  });
export { handler };

``` 
This is my package.json.
PS: CDK is used to build resources.

```
{
  "name": "qos",
  "version": "0.1.0",
  "bin": {
    "qos": "bin/qos.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@types/aws-lambda": "^8.10.86",
    
    "@types/babel__traverse": "7.18.3",
    "@types/jest": "^27.5.2",
    "@types/node": "18.11.10",
    "@types/prettier": "2.7.1",
    
    "esbuild": "^0.15.15",
    
    "jest": "^27.5.1",
    "ts-jest": "^27.1.5",
    "aws-cdk": "2.53.0",
    "ts-node": "^10.9.1",
    "typescript": "~4.2.4",

    "@aws-sdk/client-eventbridge": "^3.44.0",
    "@aws-sdk/client-ssm": "^3.44.0",
    "aws-xray-sdk-core": "^3.3.4"
  },
  "dependencies": {
    "@types/deep-diff": "^1.0.1",
    "@types/npmlog": "^4.1.3",
    "@types/xml2js": "^0.4.11",
    "@types/easy-soap-request": "^4.1.1",
    "@types/node-fetch": "^2.6.2",
    "npmlog": "^7.0.1",
    "deep-diff": "^1.0.2",
    "@aws-lambda-powertools/logger": "^1.0.1",
    "@aws-lambda-powertools/metrics": "^1.0.1",
    "@aws-lambda-powertools/tracer": "^1.0.1",
    
    "@middy/core": "^4.0.0",
    "@middy/http-json-body-parser": "^4.0.0",
    "@middy/http-error-handler": "^4.0.0",
    "@middy/http-event-normalizer": "^4.0.0",
    "@middy/http-response-serializer": "^4.0.0",
    "@middy/validator": "^4.0.0",
    "@middy/ssm": "^4.0.0",
    
    "aws-cdk-lib": "2.53.0",
    "constructs": "^10.0.0",
    "source-map-support": "^0.5.21",
    "xml2js": "^0.4.23",
    "easy-soap-request": "^5.2.0",
    "node-fetch": "^3.3.0"
  }
}
```

The lambda is used in a proxy integration with API Gateway.
The input to this handler is a regular rest API

The following errors are reported

```
2022-12-03T11:59:37.963Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "Middleware must be an object containing at least one key among \"before\", \"after\", \"onError\"",
    "stack": [
        "Error: Middleware must be an object containing at least one key among \"before\", \"after\", \"onError\"",
        "    at Function.i.use (/var/task/index.js:57:3317)",
        "    at Object.<anonymous> (/var/task/index.js:59:2630)",
        "    at Module._compile (node:internal/modules/cjs/loader:1105:14)",
        "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)",
        "    at Module.load (node:internal/modules/cjs/loader:981:32)",
        "    at Function.Module._load (node:internal/modules/cjs/loader:822:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1005:19)",
        "    at require (node:internal/modules/cjs/helpers:102:18)",
        "    at _tryRequireFile (file:///var/runtime/index.mjs:915:37)",
        "    at _tryRequire (file:///var/runtime/index.mjs:965:25)"
    ]
}

```

and

```
2022-12-03T08:59:37.964-03:00Copy2022-12-03T11:59:37.964Z	undefined	ERROR	Error: Missing AWS Lambda trace data for X-Ray. Ensure Active Tracing is enabled and no subsegments are created outside the function handler.    at Object.contextMissing (/var/task/index.js:7:16590)    at nt.Fce.t.resolveLambdaTraceData (/var/task/index.js:7:36714)    at Object.getSegment (/var/task/index.js:7:17402)    at Object.resolveSegment (/var/task/index.js:7:17107)    at s (/var/task/index.js:7:79412)    at Object.r [as request] (/var/task/index.js:7:80974)    at RAPIDClient._post (file:///var/runtime/index.mjs:514:33)    at RAPIDClient.postInitError (file:///var/runtime/index.mjs:464:14)    at Object.uncaughtException (file:///var/runtime/index.mjs:1183:14)    at process.<anonymous> (file:///var/runtime/index.mjs:1191:20) | 2022-12-03T11:59:37.964Z undefined ERROR Error: Missing AWS Lambda trace data for X-Ray. Ensure Active Tracing is enabled and no subsegments are created outside the function handler. at Object.contextMissing (/var/task/index.js:7:16590) at nt.Fce.t.resolveLambdaTraceData (/var/task/index.js:7:36714) at Object.getSegment (/var/task/index.js:7:17402) at Object.resolveSegment (/var/task/index.js:7:17107) at s (/var/task/index.js:7:79412) at Object.r [as request] (/var/task/index.js:7:80974) at RAPIDClient._post (file:///var/runtime/index.mjs:514:33) at RAPIDClient.postInitError (file:///var/runtime/index.mjs:464:14) at Object.uncaughtException (file:///var/runtime/index.mjs:1183:14) at process.<anonymous> (file:///var/runtime/index.mjs:1191:20)

```

In the middy flow the Tracer implementation of Lambda Power Tools comes first. It seems like a proper integration is lacking or they are conflicting.

Expected behavior is for the SSM Parameter to be populated in the context and the SSM call be recorded by x-ray to evaluate the latency.

Node runtime in lambda is aws_lambda.Runtime.NODEJS_16_X,

**Comment by willfarrell** [comment]
Few things going on here:
1. Getting an error: I don't think this error, `Middleware must be an object containing at least one key among \"before\", \"after\", \"onError\"`, is because of ssm. Change `inputSchema` to `eventSchema` in your validator middleware.Because we now support `contextSchema` which is part of the input, we renamed the schema option for clarity.
2. powertools tracing not connected to other middleware: `@aws-lambda-powertools/tracer` middleware is built to create a trace of the handler itself. Other middleware are isolated from it. Thus, they don't work together that way. Having tighter integration with powertools is something I hope we can do in the future after Otel has been finalized (https://github.com/awslabs/aws-lambda-powertools-typescript/discussions/665)
3. How to add in tracing: To enable tracing of a middleware that uses and AWS service you can use `awsClientCapture` (you might be able to pass `tracer` into this) or pass in a preconfigured AWS client into `AwsClient` (https://middy.js.org/docs/middlewares/ssm). I haven't tried using the powertools tracer on AWS service middlewares yet. If you're successful, a PR with an example to either of our projects would likely be helpful to others.
4. For your question around missing dependencies; we don't include the AWS SDK as it's built into the runtime and allows you to control the version. Maybe we should make them peerDependencies?
nodejs16.x has `aws-sdk@2`
nodejs18.x has `@aws-sdk/*@3`

cc @dreamorosi

**Comment by dreamorosi** [comment]
Hi @marcioemiranda, just FYI, if you are using Lambda Powertools for TypeScript I recommend you to use Middy `2.5.x` or earlier.

We haven't tested newer versions and as such we cannot guarantee compatibility. We might be able to support Middy 3.x once we drop Nodejs12 in the coming weeks, but official support for Middy 4.x is not likely to come anytime soon since we are committed to support all active AWS Lambda runtimes (currently Nodejs 14, 16, and 18).

Also, as a side note, we are working on a Parameters Utility in Powertools that will support parameters from SSM, Secrets Manager, DynamoDB, and AppConfig. You can follow the progress in [this milestone](https://github.com/awslabs/aws-lambda-powertools-typescript/milestone/8).

**Comment by marcioemiranda** [comment]
Hi @dreamorosi thanks for the comment.
Please notice that the typescript serverless sample application written by AWS is using middy v3.1.
https://github.com/aws-samples/serverless-typescript-demo/blob/main/package.json
I am using 3.6.2 and it is working fine.

@willfarrell, after adding aws-sdk v2 to my dev dependencies I was able to build the project. The middleware is working fine now. At cold starts it complains about not having a tracer set up.

@dreamorosi it would be great if the parameter utility would integrate well with LPT tracer utility.

Under load tests, the setup with middy ssm performed a little better than the one with SSM Lambda Extension.

**Comment by willfarrell** [comment]
I think this is resolved. If you think additional documentation should be added, we'd love to have a PR to improve them.
