### ISSUE TITLE
Proposal: json body parser may throw unsupported media type

### ISSUE THREAD

**Issue by fancywriter** [middyjs/middy#975]
Current implementation of JSON body parser is the following
https://github.com/middyjs/middy/blob/02210765f9154584c242e4440d086abcf3321028/packages/http-json-body-parser/index.js#L14-L16

If content type does not satisfy regular expression, it simply return nothing and do nothing. I understand this could be useful if we allow more than one content type for the same request (say JSON + XML), and one can chain parsers this way.

I would like it to be configurable to throw 415 error code https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415 if I allow only that content type and forbid everything else. I think this can be done backward-compatible way if one adds a boolean variable to opts.

**Comment by willfarrell** [comment]
Throwing an error can be accomplished by having `Content-Type` included in the eventSchema when using `@middy/validator`. This won't throw a 415 though. Do you have a use case that requires this? By throwing a 415 early, other errors in the request can only be caught on subsequent requests. Maybe a new middleware for catching `Content-Type` is required, just for throwing 415?

I'm not opposed to the idea, it would just have to be applied consistently across all middlewares that have a `mimePattern` check. Should the default be throwing 415? Update for a future major change?

We use 422 in some places when parsing fails, wondering if 415 is better suited in some of those situations.

**Comment by willfarrell** [comment]
I've done some reflecting on this. I think it should be implemented and be enforced by default (eventually). The option will likely be `disableContentTypeError`, unless I hear of a better name.

Middlewares:
- http-multipart-body-parser
- http-urlencoded-body-parser
- http-json-body-parser

TODO:
- [ ] add in new option (default true, for now)
- [ ] add in new error message
- [ ] add in new unit test
- [ ] update 422 to 415
- [ ] update 422 unit test
- [ ] update documentation

If you'd like to put a PR together, let me know. It should be a pretty easy one. Otherwise, it might take me a week or two to get around to this.

**Comment by willfarrell** [comment]
Can you take a look at PR https://github.com/middyjs/middy/pull/982, let me know what you think.
