### ISSUE TITLE
extend cors to also handle preflights

### ISSUE THREAD

**Issue by logemann** [middyjs/middy#977]
**Is your feature request related to a problem? Please describe.**
With the current state, even though somebody uses cors middleware, in his handler function he needs to handle the OPTION preflight request manually.

**Describe the solution you'd like**
Extend cors middleware to react on the OPTION request in "before" cycle so that the users handler function dont need to do it.

**Describe alternatives you've considered**
None

**Additional context**
Tell me what you think of it. Looks like an obvious feature in that middleware to me.

**Comment by willfarrell** [comment]
Sounds like great improvement, that should be on by default. The use case that comes to mind is when someone wants to dynamically set the `Access-Control-Allow-Origin` based on the `X-Api-Key` (or similar). Some logic might need to be changed to handle this use case. Because of this, it _might_ be considered a breaking change, will need to reflect and see if anyone else comments. 

Personally in my APIG I have a dedicated endpoint for `OPTIONS /{proxy+}` with a dedicated lambda that's super bare bones to ensure it's super fast, so I never thought about having `before` short circuit.

I'd be open to a PR for this, interested?

**Comment by logemann** [comment]
I created a super small enhancements locally which i tested today. Happy to create a PR for this.

**Comment by logemann** [comment]
here we go: https://github.com/middyjs/middy/pull/979

**Comment by dave-irvine** [comment]
Ah, exactly what I came to open an issue about!

> Personally in my APIG I have a dedicated endpoint for OPTIONS /{proxy+} with a dedicated lambda that's super bare bones to ensure it's super fast, so I never thought about having before short circuit.

Oh you have just saved me. so. much. time.
