### ISSUE TITLE
Middlewares don't skip events without the headers field

### ISSUE THREAD

**Issue by louislatreille** [middyjs/middy#984]
**Describe the bug**
I've recently upgraded to the latest version (4.0.9) coming from version 2.5.7. In the older version, all middlewares were checking if the `headers` field was present before doing anything. In version 3.0.0, that was dropped for some reason.

Taking `http-json-body-parser` as an example:

Old code:
```
const contentTypeHeader = headers?.['Content-Type'] ?? headers?.['content-type']
```

New code:
```
const contentType = headers['Content-Type'] ?? headers['content-type']
```

Is there any particular reason why this was done?

For the majority of cases, the new behavior is fine, as you would use a lambda function for one source only, i.e. as an API gateway proxy **OR** for other AWS services. But I have a few cases where I reuse the exact same lambda for multiple AWS service sources, such as both for an API gateway proxy lambda **AND** for a step function. With the new middleware versions, the latter now fails because there is no `headers` field in the received event.

**Environment (please complete the following information):**
 - Node.js: 16
 - Middy: 3.0.0 and up

**Comment by willfarrell** [comment]
`http-json-body-parser` and other middlewares that are prefixed with `http-` are to be used with valid AWS HTTP Events (v1 or v2). `http-json-body-parser` requires a valid `Content-Type` header to parse the body.

The change was made to remove unnecessary checks because all valid events include headers. You'll even notice `event.headers ??= {}` was removed from `http-normalizer` for the same reason.

Does your step function trigger the lambda with the body as a string or already parsed? Does it include other parts of the event like the version number, method, and path? Are you validating your inputs as strictly as possible? Updating your step function to send a properly formatted event and validating that event within the lambda will ensure you're following good security practice. Or call API Gateway from the step function (https://docs.aws.amazon.com/step-functions/latest/dg/connect-api-gateway.html).

**Comment by louislatreille** [comment]
Thanks for your response @willfarrell !

In fact, there is no issue with the event that the step function pass to the lambda. It is already parsed and contains everything I need. My issue is more that with the latest version of Middy, it started failing because the check for the `headers` field was removed.

I totally understand that middlewares prefixed with `http-` should be used with valid events that contain the headers field. What I don't want to do is have two separate lambda functions with the exact same code except for Middy, and use one with my API gateway and the other one with my Step Function. This seems like excessive toil to me.

What I ended up doing is adding a custom middleware that simply adds the `headers` field if it is not present:

```
  if (fillInHeadersField) {
    middyfiedHandler.use({
      before: async(request) => {
        if (!request.event.headers) {
          request.event.headers = {};
        }
      },
    });
  }

  middyfiedHandler
    .use(httpHeaderNormalizer())
    .use(httpJsonBodyParser())
    .use(httpSecurityHeaders())
...
```
